export const shoeArray = [
  // sale
  {
    name: "Lailas Hikers",
    tag: "lailashikers",
    image: "placeholder-min",
    price: 89,
    inCart: 0,
  },
  {
    name: "Thors Hikers",
    tag: "thorshikers",
    image: "placeholder-min",
    price: 86,
    inCart: 0,
  },
  {
    name: "Yolandas Hikers",
    tag: "yolandashikers",
    image: "placeholder-min",
    price: 86,
    inCart: 0,
  },
  {
    name: "Thomas Hikers",
    tag: "thomashikers",
    image: "placeholder-min",
    price: 99,
    inCart: 0,
  },
  // sneakers
  {
    name: "Oles Sneakers",
    tag: "olessneakers",
    image: "placeholder-min",
    price: 50,
    inCart: 0,
  },
  {
    name: "James Shoe",
    tag: "jamesshoe",
    image: "placeholder-min",
    price: 70,
    inCart: 0,
  },
  {
    name: "Thors Shoe",
    tag: "thorsshoe",
    image: "placeholder-min",
    price: 75,
    inCart: 0,
  },
  {
    name: "Reign Sneakers",
    tag: "reignsneakers",
    image: "placeholder-min",
    price: 90,
    inCart: 0,
  },
  {
    name: "Load Sneakers",
    tag: "loadsneakers",
    image: "placeholder-min",
    price: 100,
    inCart: 0,
  },
  // boots
  {
    name: "Jasmine Boots",
    tag: "jasmineboots",
    image: "placeholder-min",
    price: 100,
    inCart: 0,
  },
  {
    name: "Kit Boots",
    tag: "kitboots",
    image: "placeholder-min",
    price: 110,
    inCart: 0,
  },
  {
    name: "Chusion Boots",
    tag: "chusionboots",
    image: "placeholder-min",
    price: 80,
    inCart: 0,
  },
  {
    name: "Original Boots",
    tag: "originalboots",
    image: "placeholder-min",
    price: 85,
    inCart: 0,
  },
  // hiking
  {
    name: "Trail Hikers",
    tag: "trailhikers",
    image: "placeholder-min",
    price: 65,
    inCart: 0,
  },
  {
    name: "Blaze Hikers",
    tag: "blazehikers",
    image: "placeholder-min",
    price: 89,
    inCart: 0,
  },
  {
    name: "Jon Hikers",
    tag: "jonhikers",
    image: "placeholder-min",
    price: 99,
    inCart: 0,
  },
  {
    name: "Cami Hikers",
    tag: "camihikers",
    image: "placeholder-min",
    price: 100,
    inCart: 0,
  },
  {
    name: "Lexa Hikers",
    tag: "lexahikers",
    image: "placeholder-min",
    price: 110,
    inCart: 0,
  },
  {
    name: "Laila Hikers",
    tag: "lailahikers",
    image: "placeholder-min",
    price: 55,
    inCart: 0,
  },
  // trainers
  {
    name: "Tron Trainers",
    tag: "trontrainers",
    image: "placeholder-min",
    price: 60,
    inCart: 0,
  },
  {
    name: "Sams Trainers",
    tag: "samstrainers",
    image: "placeholder-min",
    price: 66,
    inCart: 0,
  },
  {
    name: "Karitas Trainers",
    tag: "karitastrainers",
    image: "placeholder-min",
    price: 100,
    inCart: 0,
  },
  {
    name: "Max Trainers",
    tag: "maxtrainers",
    image: "placeholder-min",
    price: 68,
    inCart: 0,
  },
  // loafers
  {
    name: "Comfy Loafers",
    tag: "comfyloafers",
    image: "placeholder-min",
    price: 90,
    inCart: 0,
  },
  {
    name: "Classy Loafers",
    tag: "classyloafers",
    image: "placeholder-min",
    price: 100,
    inCart: 0,
  },
  {
    name: "Boeng Loafers",
    tag: "boengloafers",
    image: "placeholder-min",
    price: 100,
    inCart: 0,
  },
  {
    name: "Air Loafers",
    tag: "airloafers",
    image: "placeholder-min",
    price: 110,
    inCart: 0,
  },
  {
    name: "Coding Loafers",
    tag: "codingloafers",
    image: "placeholder-min",
    price: 200,
    inCart: 0,
  },
];
